# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - build
  - release
  - deploy

variables:
  PROJECT_NAME: '${CI_PROJECT_NAME}'
  IMAGE_NAME: '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}'
  
build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build --pull -t ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG} .
    - docker push ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG}
  tags:
    - dev-docker

release-job:
  stage: release
  image: docker:stable
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
  script:
    - docker pull ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG}
    - docker login -u ${DH_REGISTRY_USER} -p ${DH_REGISTRY_PASSWORD} ${DH_REGISTRY}
    - docker image tag ${IMAGE_NAME}:${CI_COMMIT_REF_SLUG} ${CI_PROJECT_PATH}:latest
    - docker push ${CI_PROJECT_PATH}:latest
  tags:
    - dev-docker

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  image: docker:stable
  before_script:
    - docker login -u ${DH_REGISTRY_USER} -p ${DH_REGISTRY_PASSWORD} ${DH_REGISTRY}
    - cp $DOCKER_CACERT ~/ca.pem && cp $DOCKER_CERT ~/cert.pem && cp $DOCKER_KEY ~/key.pem
    - export DOCKER_HOST=tcp://192.168.244.185:2376 DOCKER_TLS_VERIFY=1
    - docker stop ${CI_PROJECT_NAME} || true
    - docker rm ${CI_PROJECT_NAME} || true
    - docker rmi ${CI_PROJECT_PATH}:latest
    - docker pull ${CI_PROJECT_PATH}:latest
    
#  services:
#    - docker:dind
  
#  environment: production
  script:
    - docker run --name ${CI_PROJECT_NAME} -d -p 127.0.0.1:1313:1313 --restart unless-stopped ${CI_PROJECT_PATH}:latest
    - docker pull ${CI_PROJECT_PATH}:latest
    - echo "Application successfully deployed."
  tags:
    - dev-docker
